---
- name: 'uninstall old git'
  yum: name='git' state=absent

- name: 'install the git'
  shell: |
    wget https://www.kernel.org/pub/software/scm/git/git-2.2.1.tar.gz
    tar xvzf git-2.2.1.tar.gz
    cd git-2.2.1
    ./configure
    make
    make install

